Refactored the fsScanner into a separate package
Jille/rufs1 pull request #19
Opened 2018-12-27 20:54 UTC by Jille

Had to introduce a common package to share some types/funcs

The new version does basically the same but is split up in many more functions which I'm told makes things more readable.
It also allows for multiple listeners which will make multi-master easier one day.
It also allows for multiple shares to be implemented in a cleaner way.

2018-12-28 13:24 UTC, dsprenkels approved these changes
All my suggestions are included in 32e0275e8348559de8c1f3cba4354946906b533b.

2018-12-28 14:23 UTC, dsprenkels commented
Btw. Could it be possible to merge https://github.com/Jille/rufs/pull/16 into this PR? I feel this PR is going to break that one.

2018-12-28 14:37 UTC, Jille commented on Gopkg.lock
> +[[projects]]
I don't think this should be added?

2018-12-28 14:44 UTC, dsprenkels commented on Gopkg.lock
> +[[projects]]
I dunno? `dep ensure` generated this file for me.

2018-12-28 14:46 UTC, dsprenkels requested changes
I seem to be getting a data race with these changes:

```
dec 28 15:43:06 roku systemd[1]: Stopping RUFS katarastorage export...
dec 28 15:43:06 roku rufs[5003]: ==================
dec 28 15:43:06 roku rufs[5003]: WARNING: DATA RACE
dec 28 15:43:06 roku rufs[5003]: Write at 0x00c42028ec60 by goroutine 15:
dec 28 15:43:06 roku rufs[5003]:   runtime.closechan()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/runtime/chan.go:325 +0x0
dec 28 15:43:06 roku rufs[5003]:   main.(*Server).Run()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/server.go:141 +0x137
dec 28 15:43:06 roku rufs[5003]:   main.main.func1()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/main.go:111 +0x48
dec 28 15:43:06 roku rufs[5003]: Previous read at 0x00c42028ec60 by goroutine 22:
dec 28 15:43:06 roku rufs[5003]:   runtime.chansend()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/runtime/chan.go:140 +0x0
dec 28 15:43:06 roku rufs[5003]:   main.(*Server).SetFile-fm()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/server.go:171 +0xa4
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.(*Scanner).set()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:100 +0x527
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.(*Scanner).normalPass.func1()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:176 +0x4e5
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.scanFilesystemAndReportMissing.func1()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:223 +0x9f
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.scanFilesystem.func1()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:247 +0x3c8
dec 28 15:43:06 roku rufs[5003]:   path/filepath.walk()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/path/filepath/path.go:357 +0x501
dec 28 15:43:06 roku rufs[5003]:   path/filepath.walk()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x3b6
dec 28 15:43:06 roku rufs[5003]:   path/filepath.walk()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x3b6
dec 28 15:43:06 roku rufs[5003]:   path/filepath.walk()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x3b6
dec 28 15:43:06 roku rufs[5003]:   path/filepath.walk()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x3b6
dec 28 15:43:06 roku rufs[5003]:   path/filepath.Walk()
dec 28 15:43:06 roku rufs[5003]:       /usr/lib/go-1.10/src/path/filepath/path.go:403 +0x14a
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.scanFilesystem()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:229 +0xde
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.scanFilesystemAndReportMissing()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:221 +0xd5
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.(*Scanner).normalPass()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:163 +0x104
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.(*Scanner).normalPassWithIntermediateAutoSaving()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:157 +0xcb
dec 28 15:43:06 roku rufs[5003]:   github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner.(*Scanner).Run()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/vendor/github.com/Jille/rufs/filescanner/filescanner.go:107 +0x7b
dec 28 15:43:06 roku rufs[5003]: Goroutine 15 (running) created at:
dec 28 15:43:06 roku rufs[5003]:   main.main()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/main.go:110 +0x459
dec 28 15:43:06 roku rufs[5003]: Goroutine 22 (running) created at:
dec 28 15:43:06 roku rufs[5003]:   main.(*Server).Run()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/server.go:138 +0x707
dec 28 15:43:06 roku rufs[5003]:   main.main.func1()
dec 28 15:43:06 roku rufs[5003]:       /home/daan/go/src/github.com/dsprenkels/rufs/main.go:111 +0x48
dec 28 15:43:06 roku rufs[5003]: ==================
```

2018-12-28 14:49 UTC, Jille commented on Gopkg.lock
> +[[projects]]
Where you at the autoip branch at the time?

2018-12-28 14:56 UTC, Jille commented
I fixed the data race at https://github.com/Jille/rufs/pull/21/files#diff-34c6b408d72845d076d47126c29948d1R179

2018-12-28 15:42 UTC, dsprenkels approved these changes

2018-12-28 15:45 UTC, merged

2021-05-22 18:42 UTC, sgielen commented
As of 640c401637929d7adf2daba27ece5c7465af09d8 the software version is displayed in logs, UI and API calls to discovery. #24 covers metrics.