Migrate repo from mrngm/rufs to Jille/rufs
Jille/rufs1 pull request #4
Opened 2018-10-05 13:08 UTC by dsprenkels

This PR migrates the code from @mrngm's repo to @Jille's repo. After merging, we should also merge the issue list.

2018-10-05 13:10 UTC, mrngm requested changes
LGTM, small thing in the README that should be addressed.

2018-10-05 13:10 UTC, mrngm commented on README.md
> +[![Build Status](https://travis-ci.org/mrngm/rufs.svg?branch=master)](https://travis-ci.org/mrngm/rufs)
This line shouldn't be included.

2018-10-10 11:51 UTC, dsprenkels commented
I updated `'mrngm'` to `'Jille'` everywhere in the source tree.

2018-10-23 07:38 UTC, mrngm approved these changes

2018-10-23 07:38 UTC, merged